name: DeployMEU para páginas do Github

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Criar artefatos para DeployMEU
        uses: actions/configure-pages@v4
        with:
          path: .
        
      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v5
        
